# Set global configuration arguments
cask_args appdir: "/Applications"

# taps
tap "caskroom/cask"
tap "caskroom/fonts"
tap "caskroom/versions"

# dependencies
brew "mas"
brew "dockutil"
brew "mackup"

# quicklook plugins
cask "qlcolorcode"
cask "qlstephen"
cask "qlmarkdown"
cask "quicklook-json"
cask "qlimagesize"
cask "qlvideo"

# shells
brew "bash"

# development
brew "node"
cask "ngrok"

# fonts
cask "font-montserrat"
cask "font-open-sans"
cask "font-pacifico"
cask "font-lato"

# install apps
cask "1password"
# cask "alfred"
# cask "bartender"
# cask "catch"
cask "cheatsheet"
cask "dropbox"
# cask "firefox"
# cask "firefox-developer-edition"
# cask "franz"
cask "google-chrome"
cask "hazel"
# cask "little-snitch"
cask "lunar"
# cask "unlox"
cask "macdropany"
cask "openpht"
cask "plex-media-server"
cask "podcastmenu"
cask "rocket"
cask "sketch"
cask "sourcetree"
# cask "spotifree"
cask "spotify"
# cask "textexpander"
cask "the-unarchiver"
cask "transmission"
# cask "tunnelblick"
# cask "tweeten"
cask "visual-studio-code"
cask "vlc"

# install mac app store apps
mas "BetterSnapTool", id: 417375580
mas "DaisyDisk", id: 411643860
mas "Reeder", id: 880001334
mas "Spark", id: 1176895641
# mas "Xcode", id: 497799835
